pull_request_rules:
  - name: automatic merge
    conditions:
      - author=@devs
      - label=automerge
      - check-success=test
    actions:
      merge:
        method: merge
        
  - name: add label on javascript pr
    conditions:
      - files~=javascript
    actions:
      label:
        add:
          - javascript

  - name: assign PRs with Python files modified to sileht
    conditions:
      - files~=\.py$
      - -closed
    actions:
      assign:
        add_users:
          - another-jd

  - name: clean branches
    conditions: []
    actions:
      delete_head_branch:

  - name: automatic queue for merge
    conditions:
      - author=@devs
      - files~=^testbed/queue
      - check-success=test
    actions:
      queue:
        name: default
        
queue_rules:
  - name: default
    conditions:
     # Fake schedule
     - schedule=Mon-Sun
